export { Header } from './header'
export { About } from './about'
export { Hero } from './hero'
export { Footer } from './footer'
export { Services } from './services'
export { HeaderContact } from './headerContact'